# Site settings
title: 淡定的程序猿的博客
SEOTitle: 淡定的程序猿的博客 | BY Quanwe
header-img: img/acg/67650124.webp
email: weiquan@163.com
author-name: 淡定的程序猿
description: "Every failure is leading towards success."
keyword: "BY, BY Quanwe, 淡定的程序猿的博客, 程序猿,Quanwe, wq, Android, Google,Android Studio"
url: "http://976112643.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/976112643/976112643.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     2909669001
zhihu_username:     yuan-dong-5-26
github_username:    976112643
#facebook_username:  
jianshu_username:   b0d50c26181c
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
#redcarpet: extensions: ["hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统




# Analytics settings
# Baidu Analytics
#ba_track_id: 401abaf8c55fef6fc2160e9354999677

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#00ad81"
service-worker: true


#github Site
github-site: "http://976112643.github.io"

# 默认的头部图片,页面不设置头部图片时,自动再该数组里边选取
header-imgs: [
#	"img/acg/67650124.webp",
	"img/post-bg-hacker.jpg",
	"img/post-bg-iWatch.jpg",
	"img/post-bg-debug.png",
	"img/post-bg-github-cup.jpg"
]

# 首页默认图片
index-header-img: "img/post-bg-github-cup.jpg"

# 是否显示春菜
weichuncai-show: false     

# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
